version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: task_manager_postgres
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: taskManager
      POSTGRES_DB: task_manager
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pg.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  pgdata:
